Add app data (name, description, version)

diff --git a/vpnmgr b/vpnmgr
--- a/vpnmgr
+++ b/vpnmgr
@@ -1,31 +1,44 @@
 #!/usr/bin/env bash
-
+#
 # Name:         vpnmgr
 # Description:  Create and delete OpenVPN client configurations
 # OS:           CentOS 7
-# Author:        <Dmitry V.> dmitry.vlasov@fastmail.com
+# Author:       <Dmitry V.> dmitry.vlasov@fastmail.com
+# Version:      0.1
+
+declare -rA app=(
+    ["name"]="vpnmgr"
+    ["description"]="Create and delete OpenVPN client configurations"
+    ["version"]="0.1"
+)
 
 function usage() {
-    echo "Usage: vpnmgr command [options] 
-   
+    echo "Usage: vpnmgr command [options]
+${app['description']}
+
 Commands:
     create       Create the client configuration
     delete       Delete the client configuration
     status       Show existing configurations and their status
     help         Show this message
+    version      Show the version
 
 Options:
     vpnmgr (create|delete) name
         name     Client configuration name
-    
+
     vpnmgr status [name]
         name     Client configuration name (if empty, show a list of configurations)"
+}
+
+function version() {
+    echo "${app['name']} ${app['version']}"
 }
 
 
 function root_check() {
     if [[ $EUID -ne 0 ]]; then
-       echo "This script must be run as root" 
+       echo "This script must be run as root"
        exit 1
     fi
 }
@@ -40,7 +53,7 @@ function openvpn_check() {
 function printTable() {
     local -r mode=${1}
     shift 1
-    
+
     local input=""
     while [[ $# -gt 0 ]]; do
         if [[ "${2}" == "" || "${1}" == *"\n" ]]; then
@@ -50,23 +63,23 @@ function printTable() {
         fi
         shift 1
     done
-    
+
     local -r delimiter=","
     local -r input=${input}
     local -r data="$(removeEmptyLines "$input")"
-    
+
     if [[ "${delimiter}" != '' && "$(isEmptyString "${data}")" = 'false' ]]; then
         local -r numberOfLines="$(wc -l <<< "${data}")"
         if [[ "${numberOfLines}" -gt '0' ]]; then
             local table=''
             local i=1
-            
+
             for ((i = 1; i <= "${numberOfLines}"; i = i + 1)); do
                 local line=''
                 line="$(sed "${i}q;d" <<< "${data}")"
                 local numberOfColumns='0'
                 numberOfColumns="$(awk -F "${delimiter}" '{print NF}' <<< "${line}")"
-                
+
                 if [[ "$mode" == "1" ]]; then
                     if [[ "${i}" -eq '1' ]]; then
                         table="${table}$(printf '%s+' "$(repeatString '+#' "${numberOfColumns}")")"
@@ -76,7 +89,7 @@ function printTable() {
                 else
                     exit 1;
                 fi
-                
+
                 table="${table}\n"
                 local j=1
                 for ((j = 1; j <= "${numberOfColumns}"; j = j + 1)); do
@@ -86,7 +99,7 @@ function printTable() {
                         table="${table}$(printf '#| %s' "$(cut -d "${delimiter}" -f "${j}" <<< "${line}")")"
                     fi
                 done
-                
+
                 table="${table}#|\n"
                 if [[ "$mode" == "1" ]]; then
                     if [[ "${i}" -eq '1' ]] || [[ "${numberOfLines}" -gt '1' && "${i}" -eq "${numberOfLines}" ]]; then
@@ -100,7 +113,7 @@ function printTable() {
                     exit 1;
                 fi
             done
-            
+
             if [[ "$(isEmptyString "${table}")" = 'false' ]]; then
                 echo -e "${table}" | column -s '#' -t | awk '/^\+/{gsub(" ", "-", $0)}1'
             fi
@@ -116,7 +129,7 @@ function removeEmptyLines() {
 function repeatString() {
     local -r string="${1}"
     local -r numberToRepeat="${2}"
-    
+
     if [[ "${string}" != '' && "${numberToRepeat}" =~ ^[1-9][0-9]*$ ]]; then
         local -r result="$(printf "%${numberToRepeat}s")"
         echo -e "${result// /${string}}"
@@ -147,14 +160,14 @@ function create() {
         echo "Client configuration already exist"
         exit 1
     fi
-    
+
     cd /etc/openvpn/pki
     ./easyrsa gen-req ${name}
     if ! [[ -f "/etc/openvpn/pki/pki/reqs/$name.req" ]]; then
         echo "Unexpected error creating request by PKI"
         exit 1
     fi
-    
+
     cd /etc/openvpn/ca
     ./easyrsa import-req /etc/openvpn/pki/pki/reqs/${name}.req ${name}
     if ! [[ -f "/etc/openvpn/ca/pki/reqs/$name.req" ]]; then
@@ -195,7 +208,7 @@ function delete() {
         ./easyrsa gen-crl
         systemctl restart openvpn@server
     fi
-    
+
     if ! [[ -f "/etc/openvpn/clients/$name.ovpn" ]]; then
         echo "Client configuration does not exist"
         exit 1
@@ -210,11 +223,11 @@ function delete() {
 function status() {
     client_db="/etc/openvpn/client/clients.db"
     openvpn_status="/var/log/openvpn/openvpn-status.log"
-    
+
     if [[ "$mode" == "detailed" ]]; then
         declare -a column0
         declare -a column1
-        
+
         IFS=',' read -ra updated <<< $(cat ${openvpn_status} | grep "^Updated,")
         cl_name=$(cat ${client_db} | grep "^$name,")
         if [[ "$cl_name" == "" ]]; then
@@ -226,10 +239,10 @@ function status() {
         column1[0]=${client_name_temp[0]}
         column1[7]="${client_name_temp[1]}"
         cl_name=${client_name_temp[0]}
-        
+
         client_list=$(cat ${openvpn_status} | grep "^$cl_name,")
         IFS=',' read -ra client_list <<< ${client_list}
-        
+
         routing_table=$(cat ${openvpn_status} | grep --line-buffered --initial-tab ",$cl_name,")
         count=1
         for line in ${routing_table}; do
@@ -240,7 +253,7 @@ function status() {
         done
         IFS="," read -ra routing_table_ipv6 <<< ${routing_table_ipv6}
         IFS=',' read -ra routing_table <<< ${routing_table}
-        
+
         if [[ "$client_list" == "" ]]; then
             column1[1]="-"
             column1[2]="-"
@@ -284,7 +297,7 @@ function status() {
                 column1[4]="$(awk "BEGIN { printf \"%3.0f\", ${column1[4]} }") B"
             fi
         fi
-        
+
         if ! [[ "${routing_table_ipv6[0]}" == "" ]]; then
             printTable "1"  "Name"                   "${column1[0]}\n" \
                             "Virtual Address"        "${routing_table_ipv6[0]}\n" \
@@ -312,16 +325,16 @@ function status() {
         declare -a ip
         declare -a real_address
         declare -a state
-        
+
         if [[ "$(cat ${client_db})" == "" ]]; then
             printTable "2" "Name" "Virtual Address" "Real Address" "Status\n" \
                            "-" "-" "-" "-"
             exit 1
         fi
-        
+
         IFS=',' read -ra updated <<< $(cat ${openvpn_status} | grep "^Updated,")
         echo "${updated[0]}: ${updated[1]}"
-        
+
         for i in $(cat ${client_db}); do
             IFS=',' read -ra client_name_temp <<< $i
             cl_name="${client_name_temp[0]}"
@@ -329,7 +342,7 @@ function status() {
             state+=("${client_name_temp[1]}")
             client_list=$(cat ${openvpn_status} | grep "^$cl_name,")
             IFS=',' read -ra client_list <<< ${client_list}
-            
+
             routing_table=$(cat ${openvpn_status} | grep ",$cl_name,")
             count=1
             for line in ${routing_table}; do
@@ -340,7 +353,7 @@ function status() {
             done
             IFS="," read -ra routing_table_ipv6 <<< ${routing_table_ipv6}
             IFS=',' read -ra routing_table <<< ${routing_table}
-            
+
             if [[ "$client_list" == "" ]]; then
                 ip+=("-")
                 real_address+=("-")
@@ -353,7 +366,7 @@ function status() {
                 real_address_temp=${client_list[1]}
                 IFS=':' read -ra real_address_temp <<< ${real_address_temp}
                 real_address+=("${real_address_temp[0]}")
-            fi        
+            fi
         done
 
         printTable "2" "Name" "Virtual Address" "Real Address" "Status\n" \
@@ -362,30 +375,32 @@ function status() {
                          for ((i = 0 ; i < len ; i++)); do
                            echo "${client_name[$i]} ${ip[$i]} ${real_address[$i]} ${state[$i]}\n"
                          done;
-                       )        
+                       )
     fi
 }
 
 openvpn_check
 
-if [[ "$1" == "" ]]; then
-    echo -e "Create and delete OpenVPN client configurations"
-    usage
-fi
+if [[ "$1" == "" ]]; then usage; fi
 
 for i in $@; do
-    if [[ "$i" == "--help" ]]; then
-            echo -e "Create and delete OpenVPN client configurations"
+    if [[ "$i" == "--help" ]] || [[ "$i" == "-h" ]] ; then
             usage
             exit 1
+    elif [[ "$i" == "--version" ]] || [[ "$i" == "-v" ]] ; then
+        version
+        exit 1
     fi
 done
 
 while [[ $# -gt 0 ]]; do
     case "$1" in
         h|help|--help)
-            echo -e "Create and delete OpenVPN client configurations"
             usage
+            exit 1
+            ;;
+        v|version|-v|--version)
+            version
             exit 1
             ;;
         c|create)
@@ -425,8 +440,7 @@ while [[ $# -gt 0 ]]; do
             shift
             ;;
         *)
-            echo -e "Syntax"
-            usage
+            echo -e "Syntax error. See help"
             exit 1
             ;;
     esac
